---
# tasks file for php
- name: Install PHP 7 with the most common packages
  yum: 
    name: ['php', 'php-gd',
 'php-mbstring', 'php-mysqlnd', 'php-opcache', 'php-pdo',
'php-pecl-apcu']
    state: present
  notify: restart Apache 
- name: Upload index.php file to the remote web directory
  copy:
    src: index.php
    dest: /var/www/html
    owner: ec2-user
    group: ec2-user

